import unittest
import unittest
from fibonacci import fitLogPrediction, fitFibPrediction, fibList, f_Binet, nearest_saved_fib, make_saved_Fibonacci_file

class TestFibonacciFunctions(unittest.TestCase):
    def test_fitLogPrediction(self):
        # Test with sample inputs
        x = 10
        m = 1.5
        b = 2.0
        result = fitLogPrediction(x, m, b)
        self.assertAlmostEqual(result, m * x + b)
    
    def test_fitFibPrediction(self):
        # Test with sample inputs
        x = 10
        m = 1.5
        b = 2.0
        result = fitFibPrediction(x, m, b)
        self.assertAlmostEqual(result, round(math.exp(fitLogPrediction(x, m, b))))
    
    def test_fibList(self):
        # Test with sample input
        n = 10
        result = fibList(n)
        self.assertEqual(result, [0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
    
    def test_f_Binet(self):
        # Test with sample input
        n = 10
        result = f_Binet(n)
        self.assertEqual(result, 55)
    
    def test_nearest_saved_fib(self):
        # Test with sample input
        num = 10
        result = nearest_saved_fib(num)
        self.assertEqual(result, 8)
    
    def test_make_saved_Fibonacci_file(self):
        # Test if the file is created
        make_saved_Fibonacci_file()
        self.assertTrue(os.path.exists('fibonacci_numbers.bin'))
    
if __name__ == '__main__':
    unittest.main()
from fibonacci_module import fibList, is_fibonacci, f_Binet, n_Binet, nearest_Binet_fib, make_saved_Fibonacci_file, get_nth_saved_Fibonacci_number, nearest_saved_fib, nearest_saved_fib_index
from fibonacci_module import fibList, is_fibonacci, f_Binet, n_Binet, nearest_Binet_fib, make_saved_Fibonacci_file, get_nth_saved_Fibonacci_number, nearest_saved_fib, nearest_saved_fib_index


class TestFibonacciFunctions(unittest.TestCase):
class TestFibonacciModule(unittest.TestCase):
    def test_fibList(self):
    def test_integer_input(self):
        self.assertEqual(fibList(0), [])
        # Test with positive integer input
        self.assertEqual(fibList(5), [0, 1, 1, 2, 3])
        self.assertEqual(fibList(1), [0])
        # Test with negative integer input
        with self.assertRaises(ValueError):
            fibList(-5)
        self.assertEqual(fibList(2), [0, 1])
        
        self.assertEqual(fibList(3), [0, 1, 1])
    def test_float_input(self):
        self.assertEqual(fibList(4), [0, 1, 1, 2])
        # Test with float input
        with self.assertRaises(TypeError):
            fibList(5.5)
        self.assertEqual(fibList(5), [0, 1, 1, 2, 3])
        
        self.assertEqual(fibList(6), [0, 1, 1, 2, 3, 5])
    def test_non_numeric_input(self):
        self.assertEqual(fibList(7), [0, 1, 1, 2, 3, 5, 8])
        # Test with non-numeric input
        with self.assertRaises(TypeError):
            fibList("five")
        self.assertEqual(fibList(8), [0, 1, 1, 2, 3, 5, 8, 13])
        
        self.assertEqual(fibList(9), [0, 1, 1, 2, 3, 5, 8, 13, 21])
    def test_edge_cases(self):
        self.assertEqual(fibList(10), [0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
        # Test with edge case: n = 0
        self.assertEqual(fibList(0), [])

        # Test with edge case: n = 1
        self.assertEqual(fibList(1), [0])
    def test_is_fibonacci(self):
        
        self.assertTrue(is_fibonacci(0))
if __name__ == '__main__':
        self.assertTrue(is_fibonacci(1))
    unittest.main()
        self.assertTrue(is_fibonacci(1))
        self.assertTrue(is_fibonacci(2))
        self.assertTrue(is_fibonacci(3))
        self.assertTrue(is_fibonacci(5))
        self.assertTrue(is_fibonacci(8))
        self.assertTrue(is_fibonacci(13))
        self.assertTrue(is_fibonacci(21))
        self.assertTrue(is_fibonacci(34))
        self.assertFalse(is_fibonacci(4))
        self.assertFalse(is_fibonacci(6))
        self.assertFalse(is_fibonacci(7))
        self.assertFalse(is_fibonacci(9))
        self.assertFalse(is_fibonacci(10))
        self.assertFalse(is_fibonacci(11))
        self.assertFalse(is_fibonacci(12))
        self.assertFalse(is_fibonacci(14))
        self.assertFalse(is_fibonacci(15))
        self.assertFalse(is_fibonacci(16))
        self.assertFalse(is_fibonacci(17))
        self.assertFalse(is_fibonacci(18))
        self.assertFalse(is_fibonacci(19))
        self.assertFalse(is_fibonacci(20))
        self.assertFalse(is_fibonacci(22))
        self.assertFalse(is_fibonacci(23))
        self.assertFalse(is_fibonacci(24))
        self.assertFalse(is_fibonacci(25))
        self.assertFalse(is_fibonacci(26))
        self.assertFalse(is_fibonacci(27))
        self.assertFalse(is_fibonacci(28))
        self.assertFalse(is_fibonacci(29))
        self.assertFalse(is_fibonacci(30))
        self.assertFalse(is_fibonacci(31))
        self.assertFalse(is_fibonacci(32))
        self.assertFalse(is_fibonacci(33))
        self.assertFalse(is_fibonacci(35))
        self.assertFalse(is_fibonacci(36))
        self.assertFalse(is_fibonacci(37))
        self.assertFalse(is_fibonacci(38))
        self.assertFalse(is_fibonacci(39))
        self.assertFalse(is_fibonacci(40))
        self.assertFalse(is_fibonacci(41))
        self.assertFalse(is_fibonacci(42))
        self.assertFalse(is_fibonacci(43))
        self.assertFalse(is_fibonacci(44))
        self.assertFalse(is_fibonacci(45))
        self.assertFalse(is_fibonacci(46))
        self.assertFalse(is_fibonacci(47))
        self.assertFalse(is_fibonacci(48))
        self.assertFalse(is_fibonacci(49))
        self.assertFalse(is_fibonacci(50))

class TestFibonacciFunctions(unittest.TestCase):
    def test_fibList(self):
        self.assertEqual(fibList(0), [])
        # Test with positive integer input
        self.assertEqual(fibList(5), [0, 1, 1, 2, 3])
        self.assertEqual(fibList(1), [0])
        # Test with negative integer input
        with self.assertRaises(ValueError):
            fibList(-5)
        self.assertEqual(fibList(2), [0, 1])
        
        self.assertEqual(fibList(3), [0, 1, 1])
    def test_float_input(self):
        self.assertEqual(fibList(4), [0, 1, 1, 2])
        # Test with float input
        with self.assertRaises(TypeError):
            fibList(5.5)
        self.assertEqual(fibList(5), [0, 1, 1, 2, 3])
        
        self.assertEqual(fibList(6), [0, 1, 1, 2, 3, 5])
    def test_non_numeric_input(self):
        self.assertEqual(fibList(7), [0, 1, 1, 2, 3, 5, 8])
        # Test with non-numeric input
        with self.assertRaises(TypeError):
            fibList("five")
        self.assertEqual(fibList(8), [0, 1, 1, 2, 3, 5, 8, 13])
        
        self.assertEqual(fibList(9), [0, 1, 1, 2, 3, 5, 8, 13, 21])
    def test_edge_cases(self):
        self.assertEqual(fibList(10), [0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
        # Test with edge case: n = 0
        self.assertEqual(fibList(0), [])
        
        # Test with edge case: n = 1
        self.assertEqual(fibList(1), [0])
    def test_is_fibonacci(self):
        
        self.assertTrue(is_fibonacci(0))
        self.assertTrue(is_fibonacci(1))
        self.assertTrue(is_fibonacci(1))
        self.assertTrue(is_fibonacci(2))
        self.assertTrue(is_fibonacci(3))
        self.assertTrue(is_fibonacci(5))
        self.assertTrue(is_fibonacci(8))
        self.assertTrue(is_fibonacci(13))
        self.assertTrue(is_fibonacci(21))
        self.assertTrue(is_fibonacci(34))
        self.assertFalse(is_fibonacci(4))
        self.assertFalse(is_fibonacci(6))
        self.assertFalse(is_fibonacci(7))
        self.assertFalse(is_fibonacci(9))
        self.assertFalse(is_fibonacci(10))
        self.assertFalse(is_fibonacci(11))
        self.assertFalse(is_fibonacci(12))
        self.assertFalse(is_fibonacci(14))
        self.assertFalse(is_fibonacci(15))
        self.assertFalse(is_fibonacci(16))
        self.assertFalse(is_fibonacci(17))
        self.assertFalse(is_fibonacci(18))
        self.assertFalse(is_fibonacci(19))
        self.assertFalse(is_fibonacci(20))
        self.assertFalse(is_fibonacci(22))
        self.assertFalse(is_fibonacci(23))
        self.assertFalse(is_fibonacci(24))
        self.assertFalse(is_fibonacci(25))
        self.assertFalse(is_fibonacci(26))
        self.assertFalse(is_fibonacci(27))
        self.assertFalse(is_fibonacci(28))
        self.assertFalse(is_fibonacci(29))
        self.assertFalse(is_fibonacci(30))
        self.assertFalse(is_fibonacci(31))
        self.assertFalse(is_fibonacci(32))
        self.assertFalse(is_fibonacci(33))
        self.assertFalse(is_fibonacci(35))
        self.assertFalse(is_fibonacci(36))
        self.assertFalse(is_fibonacci(37))
        self.assertFalse(is_fibonacci(38))
        self.assertFalse(is_fibonacci(39))
        self.assertFalse(is_fibonacci(40))
        self.assertFalse(is_fibonacci(41))
        self.assertFalse(is_fibonacci(42))
        self.assertFalse(is_fibonacci(43))
        self.assertFalse(is_fibonacci(44))
        self.assertFalse(is_fibonacci(45))
        self.assertFalse(is_fibonacci(46))
        self.assertFalse(is_fibonacci(47))
        self.assertFalse(is_fibonacci(48))
        self.assertFalse(is_fibonacci(49))
        self.assertFalse(is_fibonacci(50))

    def test_f_Binet(self):
        self.assertEqual(f_Binet(1), 0)
        self.assertEqual(f_Binet(2), 1)
        self.assertEqual(f_Binet(3), 1)
        self.assertEqual(f_Binet(4), 2)
        self.assertEqual(f_Binet(5), 3)
        self.assertEqual(f_Binet(6), 5)
        self.assertEqual(f_Binet(7), 8)
        self.assertEqual(f_Binet(8), 13)
        self.assertEqual(f_Binet(9), 21)
        self.assertEqual(f_Binet(10), 34)

    def test_n_Binet(self):
        self.assertAlmostEqual(n_Binet(0)[0], 1)
        self.assertAlmostEqual(n_Binet(1)[0], 2)
        self.assertAlmostEqual(n_Binet(1)[0], 2)
        self.assertAlmostEqual(n_Binet(2)[0], 4)
        self.assertAlmostEqual(n_Binet(3)[0], 5)
        self.assertAlmostEqual(n_Binet(5)[0], 6)
        self.assertAlmostEqual(n_Binet(8)[0], 7)
        self.assertAlmostEqual(n_Binet(13)[0], 8)
        self.assertAlmostEqual(n_Binet(21)[0], 9)
        self.assertAlmostEqual(n_Binet(34)[0], 10)

    def test_nearest_Binet_fib(self):
        self.assertEqual(nearest_Binet_fib(0), 0)
        self.assertEqual(nearest_Binet_fib(1), 1)
        self.assertEqual(nearest_Binet_fib(1), 1)
        self.assertEqual(nearest_Binet_fib(2), 2)
        self.assertEqual(nearest_Binet_fib(3), 3)
        self.assertEqual(nearest_Binet_fib(5), 5)
        self.assertEqual(nearest_Binet_fib(8), 8)
        self.assertEqual(nearest_Binet_fib(13), 13)
        self.assertEqual(nearest_Binet_fib(21), 21)
        self.assertEqual(nearest_Binet_fib(34), 34)
        self.assertEqual(nearest_Binet_fib(4), 3)
        self.assertEqual(nearest_Binet_fib(6), 5)
        self.assertEqual(nearest_Binet_fib(7), 8)
        self.assertEqual(nearest_Binet_fib(9), 8)
        self.assertEqual(nearest_Binet_fib(10), 8)
        self.assertEqual(nearest_Binet_fib(11), 13)
        self.assertEqual(nearest_Binet_fib(12), 13)
        self.assertEqual(nearest_Binet_fib(14), 13)
        self.assertEqual(nearest_Binet_fib(15), 13)
        self.assertEqual(nearest_Binet_fib(16), 13)
        self.assertEqual(nearest_Binet_fib(17), 21)
        self.assertEqual(nearest_Binet_fib(18), 21)
        self.assertEqual(nearest_Binet_fib(19), 21)
        self.assertEqual(nearest_Binet_fib(20), 21)
        self.assertEqual(nearest_Binet_fib(22), 21)
        self.assertEqual(nearest_Binet_fib(23), 21)
        self.assertEqual(nearest_Binet_fib(24), 21)
        self.assertEqual(nearest_Binet_fib(25), 21)
        self.assertEqual(nearest_Binet_fib(26), 21)
        self.assertEqual(nearest_Binet_fib(27), 21)
        self.assertEqual(nearest_Binet_fib(28), 21)
        self.assertEqual(nearest_Binet_fib(29), 34)
        self.assertEqual(nearest_Binet_fib(30), 34)
        self.assertEqual(nearest_Binet_fib(31), 34)
        self.assertEqual(nearest_Binet_fib(32), 34)
        self.assertEqual(nearest_Binet_fib(33), 34)
        self.assertEqual(nearest_Binet_fib(35), 34)
        self.assertEqual(nearest_Binet_fib(36), 34)
        self.assertEqual(nearest_Binet_fib(37), 34)
        self.assertEqual(nearest_Binet_fib(38), 34)
        self.assertEqual(nearest_Binet_fib(39), 34)
        self.assertEqual(nearest_Binet_fib(40), 34)
        self.assertEqual(nearest_Binet_fib(41), 34)
        self.assertEqual(nearest_Binet_fib(42), 34)
        self.assertEqual(nearest_Binet_fib(43), 34)
        self.assertEqual(nearest_Binet_fib(44), 34)
        self.assertEqual(nearest_Binet_fib(45), 34)
        self.assertEqual(nearest_Binet_fib(46), 34)
        self.assertEqual(nearest_Binet_fib(47), 34)
        self.assertEqual(nearest_Binet_fib(48), 34)
        self.assertEqual(nearest_Binet_fib(49), 34)
        self.assertEqual(nearest_Binet_fib(50), 34)

    def test_make_saved_Fibonacci_file(self):
        make_saved_Fibonacci_file()
        self.assertTrue(os.path.isfile(fb.filename))

    def test_get_nth_saved_Fibonacci_number(self):
        make_saved_Fibonacci_file()
        self.assertEqual(get_nth_saved_Fibonacci_number(1), 0)
        self.assertEqual(get_nth_saved_Fibonacci_number(2), 1)
        self.assertEqual(get_nth_saved_Fibonacci_number(3), 1)
        self.assertEqual(get_nth_saved_Fibonacci_number(4), 2)
        self.assertEqual(get_nth_saved_Fibonacci_number(5), 3)
        self.assertEqual(get_nth_saved_Fibonacci_number(6), 5)
        self.assertEqual(get_nth_saved_Fibonacci_number(7), 8)
        self.assertEqual(get_nth_saved_Fibonacci_number(8), 13)
        self.assertEqual(get_nth_saved_Fibonacci_number(9), 21)
        self.assertEqual(get_nth_saved_Fibonacci_number(10), 34)

    def test_nearest_saved_fib(self):
        make_saved_Fibonacci_file()
        self.assertEqual(nearest_saved_fib(0), 0)
        self.assertEqual(nearest_saved_fib(1), 1)
        self.assertEqual(nearest_saved_fib(1), 1)
        self.assertEqual(nearest_saved_fib(2), 2)
        self.assertEqual(nearest_saved_fib(3), 3)
        self.assertEqual(nearest_saved_fib(5), 5)
        self.assertEqual(nearest_saved_fib(8), 8)
        self.assertEqual(nearest_saved_fib(13), 13)
        self.assertEqual(nearest_saved_fib(21), 21)
        self.assertEqual(nearest_saved_fib(34), 34)
        self.assertEqual(nearest_saved_fib(4), 3)
        self.assertEqual(nearest_saved_fib(6), 5)
        self.assertEqual(nearest_saved_fib(7), 8)
        self.assertEqual(nearest_saved_fib(9), 8)
        self.assertEqual(nearest_saved_fib(10), 8)
        self.assertEqual(nearest_saved_fib(11), 13)
        self.assertEqual(nearest_saved_fib(12), 13)
        self.assertEqual(nearest_saved_fib(14), 13)
        self.assertEqual(nearest_saved_fib(15), 13)
        self.assertEqual(nearest_saved_fib(16), 13)
        self.assertEqual(nearest_saved_fib(17), 21)
        self.assertEqual(nearest_saved_fib(18), 21)
        self.assertEqual(nearest_saved_fib(19), 21)
        self.assertEqual(nearest_saved_fib(20), 21)
        self.assertEqual(nearest_saved_fib(22), 21)
        self.assertEqual(nearest_saved_fib(23), 21)
        self.assertEqual(nearest_saved_fib(24), 21)
        self.assertEqual(nearest_saved_fib(25), 21)
        self.assertEqual(nearest_saved_fib(26), 21)
        self.assertEqual(nearest_saved_fib(27), 21)
        self.assertEqual(nearest_saved_fib(28), 21)
        self.assertEqual(nearest_saved_fib(29), 34)
        self.assertEqual(nearest_saved_fib(30), 34)
        self.assertEqual(nearest_saved_fib(31), 34)
        self.assertEqual(nearest_saved_fib(32), 34)
        self.assertEqual(nearest_saved_fib(33), 34)
        self.assertEqual(nearest_saved_fib(35), 34)
        self.assertEqual(nearest_saved_fib(36), 34)
        self.assertEqual(nearest_saved_fib(37), 34)
        self.assertEqual(nearest_saved_fib(38), 34)
        self.assertEqual(nearest_saved_fib(39), 34)
        self.assertEqual(nearest_saved_fib(40), 34)
        self.assertEqual(nearest_saved_fib(41), 34)
        self.assertEqual(nearest_saved_fib(42), 34)
        self.assertEqual(nearest_saved_fib(43), 34)
        self.assertEqual(nearest_saved_fib(44), 34)
        self.assertEqual(nearest_saved_fib(45), 34)
        self.assertEqual(nearest_saved_fib(46), 34)
        self.assertEqual(nearest_saved_fib(47), 34)
        self.assertEqual(nearest_saved_fib(48), 34)
        self.assertEqual(nearest_saved_fib(49), 34)
        self.assertEqual(nearest_saved_fib(50), 34)

    def test_nearest_saved_fib_index(self):
        make_saved_Fibonacci_file()
        self.assertEqual(nearest_saved_fib_index(0), 1)
        self.assertEqual(nearest_saved_fib_index(1), 2)
        self.assertEqual(nearest_saved_fib_index(1), 2)
        self.assertEqual(nearest_saved_fib_index(2), 3)
        self.assertEqual(nearest_saved_fib_index(3), 4)
        self.assertEqual(nearest_saved_fib_index(5), 5)
        self.assertEqual(nearest_saved_fib_index(8), 6)
        self.assertEqual(nearest_saved_fib_index(13), 7)
        self.assertEqual(nearest_saved_fib_index(21), 8)
        self.assertEqual(nearest_saved_fib_index(34), 9)
        self.assertEqual(nearest_saved_fib_index(4), 4)
        self.assertEqual(nearest_saved_fib_index(6), 5)
        self.assertEqual(nearest_saved_fib_index(7), 6)
        self.assertEqual(nearest_saved_fib_index(9), 6)
        self.assertEqual(nearest_saved_fib_index(10), 6)
        self.assertEqual(nearest_saved_fib_index(11), 7)
        self.assertEqual(nearest_saved_fib_index(12), 7)
        self.assertEqual(nearest_saved_fib_index(14), 7)
        self.assertEqual(nearest_saved_fib_index(15), 7)
        self.assertEqual(nearest_saved_fib_index(16), 7)
        self.assertEqual(nearest_saved_fib_index(17), 8)
        self.assertEqual(nearest_saved_fib_index(18), 8)
        self.assertEqual(nearest_saved_fib_index(19), 8)
        self.assertEqual(nearest_saved_fib_index(20), 8)
        self.assertEqual(nearest_saved_fib_index(22), 8)
        self.assertEqual(nearest_saved_fib_index(23), 8)
        self.assertEqual(nearest_saved_fib_index(24), 8)
        self.assertEqual(nearest_saved_fib_index(25), 8)
        self.assertEqual(nearest_saved_fib_index(26), 8)
        self.assertEqual(nearest_saved_fib_index(27), 8)
        self.assertEqual(nearest_saved_fib_index(28), 8)
        self.assertEqual(nearest_saved_fib_index(29), 9)
        self.assertEqual(nearest_saved_fib_index(30), 9)
        self.assertEqual(nearest_saved_fib_index(31), 9)
        self.assertEqual(nearest_saved_fib_index(32), 9)
        self.assertEqual(nearest_saved_fib_index(33), 9)
        self.assertEqual(nearest_saved_fib_index(35), 9)
        self.assertEqual(nearest_saved_fib_index(36), 9)
        self.assertEqual(nearest_saved_fib_index(37), 9)
        self.assertEqual(nearest_saved_fib_index(38), 9)
        self.assertEqual(nearest_saved_fib_index(39), 9)
        self.assertEqual(nearest_saved_fib_index(40), 9)
        self.assertEqual(nearest_saved_fib_index(41), 9)
        self.assertEqual(nearest_saved_fib_index(42), 9)
        self.assertEqual(nearest_saved_fib_index(43), 9)
        self.assertEqual(nearest_saved_fib_index(44), 9)
        self.assertEqual(nearest_saved_fib_index(45), 9)
        self.assertEqual(nearest_saved_fib_index(46), 9)
        self.assertEqual(nearest_saved_fib_index(47), 9)
        self.assertEqual(nearest_saved_fib_index(48), 9)
        self.assertEqual(nearest_saved_fib_index(49), 9)
        self.assertEqual(nearest_saved_fib_index(50), 9)

if __name__ == '__main__':
    unittest.main()

    def test_f_Binet(self):
        self.assertEqual(f_Binet(1), 0)
        self.assertEqual(f_Binet(2), 1)
        self.assertEqual(f_Binet(3), 1)
        self.assertEqual(f_Binet(4), 2)
        self.assertEqual(f_Binet(5), 3)
        self.assertEqual(f_Binet(6), 5)
        self.assertEqual(f_Binet(7), 8)
        self.assertEqual(f_Binet(8), 13)
        self.assertEqual(f_Binet(9), 21)
        self.assertEqual(f_Binet(10), 34)

    def test_n_Binet(self):
        self.assertAlmostEqual(n_Binet(0)[0], 1)
        self.assertAlmostEqual(n_Binet(1)[0], 2)
        self.assertAlmostEqual(n_Binet(1)[0], 2)
        self.assertAlmostEqual(n_Binet(2)[0], 4)
        self.assertAlmostEqual(n_Binet(3)[0], 5)
        self.assertAlmostEqual(n_Binet(5)[0], 6)
        self.assertAlmostEqual(n_Binet(8)[0], 7)
        self.assertAlmostEqual(n_Binet(13)[0], 8)
        self.assertAlmostEqual(n_Binet(21)[0], 9)
        self.assertAlmostEqual(n_Binet(34)[0], 10)

    def test_nearest_Binet_fib(self):
        self.assertEqual(nearest_Binet_fib(0), 0)
        self.assertEqual(nearest_Binet_fib(1), 1)
        self.assertEqual(nearest_Binet_fib(1), 1)
        self.assertEqual(nearest_Binet_fib(2), 2)
        self.assertEqual(nearest_Binet_fib(3), 3)
        self.assertEqual(nearest_Binet_fib(5), 5)
        self.assertEqual(nearest_Binet_fib(8), 8)
        self.assertEqual(nearest_Binet_fib(13), 13)
        self.assertEqual(nearest_Binet_fib(21), 21)
        self.assertEqual(nearest_Binet_fib(34), 34)
        self.assertEqual(nearest_Binet_fib(4), 3)
        self.assertEqual(nearest_Binet_fib(6), 5)
        self.assertEqual(nearest_Binet_fib(7), 8)
        self.assertEqual(nearest_Binet_fib(9), 8)
        self.assertEqual(nearest_Binet_fib(10), 8)
        self.assertEqual(nearest_Binet_fib(11), 13)
        self.assertEqual(nearest_Binet_fib(12), 13)
        self.assertEqual(nearest_Binet_fib(14), 13)
        self.assertEqual(nearest_Binet_fib(15), 13)
        self.assertEqual(nearest_Binet_fib(16), 13)
        self.assertEqual(nearest_Binet_fib(17), 21)
        self.assertEqual(nearest_Binet_fib(18), 21)
        self.assertEqual(nearest_Binet_fib(19), 21)
        self.assertEqual(nearest_Binet_fib(20), 21)
        self.assertEqual(nearest_Binet_fib(22), 21)
        self.assertEqual(nearest_Binet_fib(23), 21)
        self.assertEqual(nearest_Binet_fib(24), 21)
        self.assertEqual(nearest_Binet_fib(25), 21)
        self.assertEqual(nearest_Binet_fib(26), 21)
        self.assertEqual(nearest_Binet_fib(27), 21)
        self.assertEqual(nearest_Binet_fib(28), 21)
        self.assertEqual(nearest_Binet_fib(29), 34)
        self.assertEqual(nearest_Binet_fib(30), 34)
        self.assertEqual(nearest_Binet_fib(31), 34)
        self.assertEqual(nearest_Binet_fib(32), 34)
        self.assertEqual(nearest_Binet_fib(33), 34)
        self.assertEqual(nearest_Binet_fib(35), 34)
        self.assertEqual(nearest_Binet_fib(36), 34)
        self.assertEqual(nearest_Binet_fib(37), 34)
        self.assertEqual(nearest_Binet_fib(38), 34)
        self.assertEqual(nearest_Binet_fib(39), 34)
        self.assertEqual(nearest_Binet_fib(40), 34)
        self.assertEqual(nearest_Binet_fib(41), 34)
        self.assertEqual(nearest_Binet_fib(42), 34)
        self.assertEqual(nearest_Binet_fib(43), 34)
        self.assertEqual(nearest_Binet_fib(44), 34)
        self.assertEqual(nearest_Binet_fib(45), 34)
        self.assertEqual(nearest_Binet_fib(46), 34)
        self.assertEqual(nearest_Binet_fib(47), 34)
        self.assertEqual(nearest_Binet_fib(48), 34)
        self.assertEqual(nearest_Binet_fib(49), 34)
        self.assertEqual(nearest_Binet_fib(50), 34)

    def test_make_saved_Fibonacci_file(self):
        make_saved_Fibonacci_file()
        self.assertTrue(os.path.isfile(fb.filename))

    def test_get_nth_saved_Fibonacci_number(self):
        make_saved_Fibonacci_file()
        self.assertEqual(get_nth_saved_Fibonacci_number(1), 0)
        self.assertEqual(get_nth_saved_Fibonacci_number(2), 1)
        self.assertEqual(get_nth_saved_Fibonacci_number(3), 1)
        self.assertEqual(get_nth_saved_Fibonacci_number(4), 2)
        self.assertEqual(get_nth_saved_Fibonacci_number(5), 3)
        self.assertEqual(get_nth_saved_Fibonacci_number(6), 5)
        self.assertEqual(get_nth_saved_Fibonacci_number(7), 8)
        self.assertEqual(get_nth_saved_Fibonacci_number(8), 13)
        self.assertEqual(get_nth_saved_Fibonacci_number(9), 21)
        self.assertEqual(get_nth_saved_Fibonacci_number(10), 34)

    def test_nearest_saved_fib(self):
        make_saved_Fibonacci_file()
        self.assertEqual(nearest_saved_fib(0), 0)
        self.assertEqual(nearest_saved_fib(1), 1)
        self.assertEqual(nearest_saved_fib(1), 1)
        self.assertEqual(nearest_saved_fib(2), 2)
        self.assertEqual(nearest_saved_fib(3), 3)
        self.assertEqual(nearest_saved_fib(5), 5)
        self.assertEqual(nearest_saved_fib(8), 8)
        self.assertEqual(nearest_saved_fib(13), 13)
        self.assertEqual(nearest_saved_fib(21), 21)
        self.assertEqual(nearest_saved_fib(34), 34)
        self.assertEqual(nearest_saved_fib(4), 3)
        self.assertEqual(nearest_saved_fib(6), 5)
        self.assertEqual(nearest_saved_fib(7), 8)
        self.assertEqual(nearest_saved_fib(9), 8)
        self.assertEqual(nearest_saved_fib(10), 8)
        self.assertEqual(nearest_saved_fib(11), 13)
        self.assertEqual(nearest_saved_fib(12), 13)
        self.assertEqual(nearest_saved_fib(14), 13)
        self.assertEqual(nearest_saved_fib(15), 13)
        self.assertEqual(nearest_saved_fib(16), 13)
        self.assertEqual(nearest_saved_fib(17), 21)
        self.assertEqual(nearest_saved_fib(18), 21)
        self.assertEqual(nearest_saved_fib(19), 21)
        self.assertEqual(nearest_saved_fib(20), 21)
        self.assertEqual(nearest_saved_fib(22), 21)
        self.assertEqual(nearest_saved_fib(23), 21)
        self.assertEqual(nearest_saved_fib(24), 21)
        self.assertEqual(nearest_saved_fib(25), 21)
        self.assertEqual(nearest_saved_fib(26), 21)
        self.assertEqual(nearest_saved_fib(27), 21)
        self.assertEqual(nearest_saved_fib(28), 21)
        self.assertEqual(nearest_saved_fib(29), 34)
        self.assertEqual(nearest_saved_fib(30), 34)
        self.assertEqual(nearest_saved_fib(31), 34)
        self.assertEqual(nearest_saved_fib(32), 34)
        self.assertEqual(nearest_saved_fib(33), 34)
        self.assertEqual(nearest_saved_fib(35), 34)
        self.assertEqual(nearest_saved_fib(36), 34)
        self.assertEqual(nearest_saved_fib(37), 34)
        self.assertEqual(nearest_saved_fib(38), 34)
        self.assertEqual(nearest_saved_fib(39), 34)
        self.assertEqual(nearest_saved_fib(40), 34)
        self.assertEqual(nearest_saved_fib(41), 34)
        self.assertEqual(nearest_saved_fib(42), 34)
        self.assertEqual(nearest_saved_fib(43), 34)
        self.assertEqual(nearest_saved_fib(44), 34)
        self.assertEqual(nearest_saved_fib(45), 34)
        self.assertEqual(nearest_saved_fib(46), 34)
        self.assertEqual(nearest_saved_fib(47), 34)
        self.assertEqual(nearest_saved_fib(48), 34)
        self.assertEqual(nearest_saved_fib(49), 34)
        self.assertEqual(nearest_saved_fib(50), 34)

    def test_nearest_saved_fib_index(self):
        make_saved_Fibonacci_file()
        self.assertEqual(nearest_saved_fib_index(0), 1)
        self.assertEqual(nearest_saved_fib_index(1), 2)
        self.assertEqual(nearest_saved_fib_index(1), 2)
        self.assertEqual(nearest_saved_fib_index(2), 3)
        self.assertEqual(nearest_saved_fib_index(3), 4)
        self.assertEqual(nearest_saved_fib_index(5), 5)
        self.assertEqual(nearest_saved_fib_index(8), 6)
        self.assertEqual(nearest_saved_fib_index(13), 7)
        self.assertEqual(nearest_saved_fib_index(21), 8)
        self.assertEqual(nearest_saved_fib_index(34), 9)
        self.assertEqual(nearest_saved_fib_index(4), 4)
        self.assertEqual(nearest_saved_fib_index(6), 5)
        self.assertEqual(nearest_saved_fib_index(7), 6)
        self.assertEqual(nearest_saved_fib_index(9), 6)
        self.assertEqual(nearest_saved_fib_index(10), 6)
        self.assertEqual(nearest_saved_fib_index(11), 7)
        self.assertEqual(nearest_saved_fib_index(12), 7)
        self.assertEqual(nearest_saved_fib_index(14), 7)
        self.assertEqual(nearest_saved_fib_index(15), 7)
        self.assertEqual(nearest_saved_fib_index(16), 7)
        self.assertEqual(nearest_saved_fib_index(17), 8)
        self.assertEqual(nearest_saved_fib_index(18), 8)
        self.assertEqual(nearest_saved_fib_index(19), 8)
        self.assertEqual(nearest_saved_fib_index(20), 8)
        self.assertEqual(nearest_saved_fib_index(22), 8)
        self.assertEqual(nearest_saved_fib_index(23), 8)
        self.assertEqual(nearest_saved_fib_index(24), 8)
        self.assertEqual(nearest_saved_fib_index(25), 8)
        self.assertEqual(nearest_saved_fib_index(26), 8)
        self.assertEqual(nearest_saved_fib_index(27), 8)
        self.assertEqual(nearest_saved_fib_index(28), 8)
        self.assertEqual(nearest_saved_fib_index(29), 9)
        self.assertEqual(nearest_saved_fib_index(30), 9)
        self.assertEqual(nearest_saved_fib_index(31), 9)
        self.assertEqual(nearest_saved_fib_index(32), 9)
        self.assertEqual(nearest_saved_fib_index(33), 9)
        self.assertEqual(nearest_saved_fib_index(35), 9)
        self.assertEqual(nearest_saved_fib_index(36), 9)
        self.assertEqual(nearest_saved_fib_index(37), 9)
        self.assertEqual(nearest_saved_fib_index(38), 9)
        self.assertEqual(nearest_saved_fib_index(39), 9)
        self.assertEqual(nearest_saved_fib_index(40), 9)
        self.assertEqual(nearest_saved_fib_index(41), 9)
        self.assertEqual(nearest_saved_fib_index(42), 9)
        self.assertEqual(nearest_saved_fib_index(43), 9)
        self.assertEqual(nearest_saved_fib_index(44), 9)
        self.assertEqual(nearest_saved_fib_index(45), 9)
        self.assertEqual(nearest_saved_fib_index(46), 9)
        self.assertEqual(nearest_saved_fib_index(47), 9)
        self.assertEqual(nearest_saved_fib_index(48), 9)
        self.assertEqual(nearest_saved_fib_index(49), 9)
        self.assertEqual(nearest_saved_fib_index(50), 9)

if __name__ == '__main__':
    unittest.main()
# Removed duplicate import statements and class definitions
# Removed redundant if __name__ == '__main__': block
# Reformatted the code to follow standard Python conventions

import unittest
from fibonacci_module import fibList, is_fibonacci, f_Binet, n_Binet, nearest_Binet_fib, make_saved_Fibonacci_file, get_nth_saved_Fibonacci_number, nearest_saved_fib, nearest_saved_fib_index

class TestFibonacciFunctions(unittest.TestCase):
    def test_fibList(self):
        self.assertEqual(fibList(0), [])
        # Test with positive integer input
        self.assertEqual(fibList(5), [0, 1, 1, 2, 3])
        self.assertEqual(fibList(1), [0])
        # Test with negative integer input
        with self.assertRaises(ValueError):
            fibList(-5)
        self.assertEqual(fibList(2), [0, 1])
        
        self.assertEqual(fibList(3), [0, 1, 1])
    def test_float_input(self):
        self.assertEqual(fibList(4), [0, 1, 1, 2])
        # Test with float input
        with self.assertRaises(TypeError):
            fibList(5.5)
        self.assertEqual(fibList(5), [0, 1, 1, 2, 3])
        
        self.assertEqual(fibList(6), [0, 1, 1, 2, 3, 5])
    def test_non_numeric_input(self):
        self.assertEqual(fibList(7), [0, 1, 1, 2, 3, 5, 8])
        # Test with non-numeric input
        with self.assertRaises(TypeError):
            fibList("five")
        self.assertEqual(fibList(8), [0, 1, 1, 2, 3, 5, 8, 13])
        
        self.assertEqual(fibList(9), [0, 1, 1, 2, 3, 5, 8, 13, 21])
    def test_edge_cases(self):
        self.assertEqual(fibList(10), [0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
        # Test with edge case: n = 0
        self.assertEqual(fibList(0), [])
        
        # Test with edge case: n = 1
        self.assertEqual(fibList(1), [0])
    def test_is_fibonacci(self):
        
        self.assertTrue(is_fibonacci(0))
        self.assertTrue(is_fibonacci(1))
        self.assertTrue(is_fibonacci(1))
        self.assertTrue(is_fibonacci(2))
        self.assertTrue(is_fibonacci(3))
        self.assertTrue(is_fibonacci(5))
        self.assertTrue(is_fibonacci(8))
        self.assertTrue(is_fibonacci(13))
        self.assertTrue(is_fibonacci(21))
        self.assertTrue(is_fibonacci(34))
        self.assertFalse(is_fibonacci(4))
        self.assertFalse(is_fibonacci(6))
        self.assertFalse(is_fibonacci(7))
        self.assertFalse(is_fibonacci(9))
        self.assertFalse(is_fibonacci(10))
        self.assertFalse(is_fibonacci(11))
        self.assertFalse(is_fibonacci(12))
        self.assertFalse(is_fibonacci(14))
        self.assertFalse(is_fibonacci(15))
        self.assertFalse(is_fibonacci(16))
        self.assertFalse(is_fibonacci(17))
        self.assertFalse(is_fibonacci(18))
        self.assertFalse(is_fibonacci(19))
        self.assertFalse(is_fibonacci(20))
        self.assertFalse(is_fibonacci(22))
        self.assertFalse(is_fibonacci(23))
        self.assertFalse(is_fibonacci(24))
        self.assertFalse(is_fibonacci(25))
        self.assertFalse(is_fibonacci(26))
        self.assertFalse(is_fibonacci(27))
        self.assertFalse(is_fibonacci(28))
        self.assertFalse(is_fibonacci(29))
        self.assertFalse(is_fibonacci(30))
        self.assertFalse(is_fibonacci(31))
        self.assertFalse(is_fibonacci(32))
        self.assertFalse(is_fibonacci(33))
        self.assertFalse(is_fibonacci(35))
        self.assertFalse(is_fibonacci(36))
        self.assertFalse(is_fibonacci(37))
        self.assertFalse(is_fibonacci(38))
        self.assertFalse(is_fibonacci(39))
        self.assertFalse(is_fibonacci(40))
        self.assertFalse(is_fibonacci(41))
        self.assertFalse(is_fibonacci(42))
        self.assertFalse(is_fibonacci(43))
        self.assertFalse(is_fibonacci(44))
        self.assertFalse(is_fibonacci(45))
        self.assertFalse(is_fibonacci(46))
        self.assertFalse(is_fibonacci(47))
        self.assertFalse(is_fibonacci(48))

import unittest
from fibonacci import fitLogPrediction, fitFibPrediction, fibList, f_Binet, nearest_saved_fib, make_saved_Fibonacci_file

class TestFibonacciFunctions(unittest.TestCase):
    def test_fitLogPrediction(self):
        # Test with sample inputs
        x = 10
        m = 1.5
        b = 2.0
        result = fitLogPrediction(x, m, b)
        self.assertAlmostEqual(result, m * x + b)
    
    def test_fitFibPrediction(self):
        # Test with sample inputs
        x = 10
        m = 1.5
        b = 2.0
        result = fitFibPrediction(x, m, b)
        self.assertAlmostEqual(result, round(math.exp(fitLogPrediction(x, m, b))))
    
    def test_fibList(self):
        # Test with sample input
        n = 10
        result = fibList(n)
        self.assertEqual(result, [0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
    
    def test_f_Binet(self):
        # Test with sample input
        n = 10
        result = f_Binet(n)
        self.assertEqual(result, 55)
    
    def test_nearest_saved_fib(self):
        # Test with sample input
        num = 10
        result = nearest_saved_fib(num)
        self.assertEqual(result, 8)
    
    def test_make_saved_Fibonacci_file(self):
        # Test if the file is created
        make_saved_Fibonacci_file()
        self.assertTrue(os.path.exists('fibonacci_numbers.bin'))
    
if __name__ == '__main__':
    unittest.main()
        self.assertFalse(is_fibonacci(49))
        self.assertFalse(is_fibonacci(50))

    def test_f_Binet(self):
        self.assertEqual(f_Binet(1), 0)
        self.assertEqual(f_Binet(2), 1)
        self.assertEqual(f_Binet(3), 1)
        self.assertEqual(f_Binet(4), 2)
        self.assertEqual(f_Binet(5), 3)
        self.assertEqual(f_Binet(6), 5)
        self.assertEqual(f_Binet(7), 8)
        self.assertEqual(f_Binet(8), 13)
        self.assertEqual(f_Binet(9), 21)
        self.assertEqual(f_Binet(10), 34)

    def test_n_Binet(self):
        self.assertAlmostEqual(n_Binet(0)[0], 1)
        self.assertAlmostEqual(n_Binet(1)[0], 2)
        self.assertAlmostEqual(n_Binet(1)[0], 2)
        self.assertAlmostEqual(n_Binet(2)[0], 4)
        self.assertAlmostEqual(n_Binet(3)[0], 5)
        self.assertAlmostEqual(n_Binet(5)[0], 6)
        self.assertAlmostEqual(n_Binet(8)[0], 7)
        self.assertAlmostEqual(n_Binet(13)[0], 8)
        self.assertAlmostEqual(n_Binet(21)[0], 9)
        self.assertAlmostEqual(n_Binet(34)[0], 10)

    def test_nearest_Binet_fib(self):
        self.assertEqual(nearest_Binet_fib(0), 0)
        self.assertEqual(nearest_Binet_fib(1), 1)
        self.assertEqual(nearest_Binet_fib(1), 1)
        self.assertEqual(nearest_Binet_fib(2), 2)
        self.assertEqual(nearest_Binet_fib(3), 3)
        self.assertEqual(nearest_Binet_fib(5), 5)
        self.assertEqual(nearest_Binet_fib(8), 8)
        self.assertEqual(nearest_Binet_fib(13), 13)
        self.assertEqual(nearest_Binet_fib(21), 21)
        self.assertEqual(nearest_Binet_fib(34), 34)
        self.assertEqual(nearest_Binet_fib(4), 3)
        self.assertEqual(nearest_Binet_fib(6), 5)
        self.assertEqual(nearest_Binet_fib(7), 8)
        self.assertEqual(nearest_Binet_fib(9), 8)
        self.assertEqual(nearest_Binet_fib(10), 8)
        self.assertEqual(nearest_Binet_fib(11), 13)
        self.assertEqual(nearest_Binet_fib(12), 13)
        self.assertEqual(nearest_Binet_fib(14), 13)
        self.assertEqual(nearest_Binet_fib(15), 13)
        self.assertEqual(nearest_Binet_fib(16), 13)
        self.assertEqual(nearest_Binet_fib(17), 21)
        self.assertEqual(nearest_Binet_fib(18), 21)
        self.assertEqual(nearest_Binet_fib(19), 21)
        self.assertEqual(nearest_Binet_fib(20), 21)
        self.assertEqual(nearest_Binet_fib(22), 21)
        self.assertEqual(nearest_Binet_fib(23), 21)
        self.assertEqual(nearest_Binet_fib(24), 21)
        self.assertEqual(nearest_Binet_fib(25), 21)
        self.assertEqual(nearest_Binet_fib(26), 21)
        self.assertEqual(nearest_Binet_fib(27), 21)
        self.assertEqual(nearest_Binet_fib(28), 21)
        self.assertEqual(nearest_Binet_fib(29), 34)
        self.assertEqual(nearest_Binet_fib(30), 34)
        self.assertEqual(nearest_Binet_fib(31), 34)
        self.assertEqual(nearest_Binet_fib(32), 34)
        self.assertEqual(nearest_Binet_fib(33), 34)
        self.assertEqual(nearest_Binet_fib(35), 34)
        self.assertEqual(nearest_Binet_fib(36), 34)
        self.assertEqual(nearest_Binet_fib(37), 34)
        self.assertEqual(nearest_Binet_fib(38), 34)
        self.assertEqual(nearest_Binet_fib(39), 34)
        self.assertEqual(nearest_Binet_fib(40), 34)
        self.assertEqual(nearest_Binet_fib(41), 34)
        self.assertEqual(nearest_Binet_fib(42), 34)
        self.assertEqual(nearest_Binet_fib(43), 34)
        self.assertEqual(nearest_Binet_fib(44), 34)
        self.assertEqual(nearest_Binet_fib(45), 34)
        self.assertEqual(nearest_Binet_fib(46), 34)
        self.assertEqual(nearest_Binet_fib(47), 34)
        self.assertEqual(nearest_Binet_fib(48), 34)
        self.assertEqual(nearest_Binet_fib(49), 34)
        self.assertEqual(nearest_Binet_fib(50), 34)

    def test_make_saved_Fibonacci_file(self):
        make_saved_Fibonacci_file()
        self.assertTrue(os.path.isfile(fb.filename))

    def test_get_nth_saved_Fibonacci_number(self):
        make_saved_Fibonacci_file()
        self.assertEqual(get_nth_saved_Fibonacci_number(1), 0)
        self.assertEqual(get_nth_saved_Fibonacci_number(2), 1)
        self.assertEqual(get_nth_saved_Fibonacci_number(3), 1)
        self.assertEqual(get_nth_saved_Fibonacci_number(4), 2)
        self.assertEqual(get_nth_saved_Fibonacci_number(5), 3)
        self.assertEqual(get_nth_saved_Fibonacci_number(6), 5)
        self.assertEqual(get_nth_saved_Fibonacci_number(7), 8)
        self.assertEqual(get_nth_saved_Fibonacci_number(8), 13)
        self.assertEqual(get_nth_saved_Fibonacci_number(9), 21)
        self.assertEqual(get_nth_saved_Fibonacci_number(10), 34)

    def test_nearest_saved_fib(self):
        make_saved_Fibonacci_file()
        self.assertEqual(nearest_saved_fib(0), 0)
        self.assertEqual(nearest_saved_fib(1), 1)
        self.assertEqual(nearest_saved_fib(1), 1)
        self.assertEqual(nearest_saved_fib(2), 2)
        self.assertEqual(nearest_saved_fib(3), 3)
        self.assertEqual(nearest_saved_fib(5), 5)
        self.assertEqual(nearest_saved_fib(8), 8)
        self.assertEqual(nearest_saved_fib(13), 13)
        self.assertEqual(nearest_saved_fib(21), 21)
        self.assertEqual(nearest_saved_fib(34), 34)
        self.assertEqual(nearest_saved_fib(4), 3)
        self.assertEqual(nearest_saved_fib(6), 5)
        self.assertEqual(nearest_saved_fib(7), 8)
        self.assertEqual(nearest_saved_fib(9), 8)
        self.assertEqual(nearest_saved_fib(10), 8)
        self.assertEqual(nearest_saved_fib(11), 13)
        self.assertEqual(nearest_saved_fib(12), 13)
        self.assertEqual(nearest_saved_fib(14), 13)
        self.assertEqual(nearest_saved_fib(15), 13)
        self.assertEqual(nearest_saved_fib(16), 13)
        self.assertEqual(nearest_saved_fib(17), 21)
        self.assertEqual(nearest_saved_fib(18), 21)
        self.assertEqual(nearest_saved_fib(19), 21)
        self.assertEqual(nearest_saved_fib(20), 21)
        self.assertEqual(nearest_saved_fib(22), 21)
        self.assertEqual(nearest_saved_fib(23), 21)
        self.assertEqual(nearest_saved_fib(24), 21)
        self.assertEqual(nearest_saved_fib(25), 21)
        self.assertEqual(nearest_saved_fib(26), 21)
        self.assertEqual(nearest_saved_fib(27), 21)
        self.assertEqual(nearest_saved_fib(28), 21)
        self.assertEqual(nearest_saved_fib(29), 34)
        self.assertEqual(nearest_saved_fib(30), 34)
        self.assertEqual(nearest_saved_fib(31), 34)
        self.assertEqual(nearest_saved_fib(32), 34)
        self.assertEqual(nearest_saved_fib(33), 34)
        self.assertEqual(nearest_saved_fib(35), 34)
        self.assertEqual(nearest_saved_fib(36), 34)
        self.assertEqual(nearest_saved_fib(37), 34)
        self.assertEqual(nearest_saved_fib(38), 34)
        self.assertEqual(nearest_saved_fib(39), 34)
        self.assertEqual(nearest_saved_fib(40), 34)
        self.assertEqual(nearest_saved_fib(41), 34)
        self.assertEqual(nearest_saved_fib(42), 34)
        self.assertEqual(nearest_saved_fib(43), 34)
        self.assertEqual(nearest_saved_fib(44), 34)
        self.assertEqual(nearest_saved_fib(45), 34)
        self.assertEqual(nearest_saved_fib(46), 34)
        self.assertEqual(nearest_saved_fib(47), 34)
        self.assertEqual(nearest_saved_fib(48), 34)
        self.assertEqual(nearest_saved_fib(49), 34)
        self.assertEqual(nearest_saved_fib(50), 34)

    def test_nearest_saved_fib_index(self):
        make_saved_Fibonacci_file()
        self.assertEqual(nearest_saved_fib_index(0), 1)
        self.assertEqual(nearest_saved_fib_index(1), 2)
        self.assertEqual(nearest_saved_fib_index(1), 2)
        self.assertEqual(nearest_saved_fib_index(2), 3)
        self.assertEqual(nearest_saved_fib_index(3), 4)
        self.assertEqual(nearest_saved_fib_index(5), 5)
        self.assertEqual(nearest_saved_fib_index(8), 6)
        self.assertEqual(nearest_saved_fib_index(13), 7)
        self.assertEqual(nearest_saved_fib_index(21), 8)
        self.assertEqual(nearest_saved_fib_index(34), 9)
        self.assertEqual(nearest_saved_fib_index(4), 4)
        self.assertEqual(nearest_saved_fib_index(6), 5)
        self.assertEqual(nearest_saved_fib_index(7), 6)
        self.assertEqual(nearest_saved_fib_index(9), 6)
        self.assertEqual(nearest_saved_fib_index(10), 6)
        self.assertEqual(nearest_saved_fib_index(11), 7)
        self.assertEqual(nearest_saved_fib_index(12), 7)
        self.assertEqual(nearest_saved_fib_index(14), 7)
        self.assertEqual(nearest_saved_fib_index(15), 7)
        self.assertEqual(nearest_saved_fib_index(16), 7)
        self.assertEqual(nearest_saved_fib_index(17), 8)
        self.assertEqual(nearest_saved_fib_index(18), 8)
        self.assertEqual(nearest_saved_fib_index(19), 8)
        self.assertEqual(nearest_saved_fib_index(20), 8)
        self.assertEqual(nearest_saved_fib_index(22), 8)
        self.assertEqual(nearest_saved_fib_index(23), 8)
        self.assertEqual(nearest_saved_fib_index(24), 8)
        self.assertEqual(nearest_saved_fib_index(25), 8)
        self.assertEqual(nearest_saved_fib_index(26), 8)
        self.assertEqual(nearest_saved_fib_index(27), 8)
        self.assertEqual(nearest_saved_fib_index(28), 8)
        self.assertEqual(nearest_saved_fib_index(29), 9)
        self.assertEqual(nearest_saved_fib_index(30), 9)
        self.assertEqual(nearest_saved_fib_index(31), 9)
        self.assertEqual(nearest_saved_fib_index(32), 9)
        self.assertEqual(nearest_saved_fib_index(33), 9)
        self.assertEqual(nearest_saved_fib_index(35), 9)
        self.assertEqual(nearest_saved_fib_index(36), 9)
        self.assertEqual(nearest_saved_fib_index(37), 9)
        self.assertEqual(nearest_saved_fib_index(38), 9)
        self.assertEqual(nearest_saved_fib_index(39), 9)
        self.assertEqual(nearest_saved_fib_index(40), 9)
        self.assertEqual(nearest_saved_fib_index(41), 9)
        self.assertEqual(nearest_saved_fib_index(42), 9)
        self.assertEqual(nearest_saved_fib_index(43), 9)
        self.assertEqual(nearest_saved_fib_index(44), 9)
        self.assertEqual(nearest_saved_fib_index(45), 9)
        self.assertEqual(nearest_saved_fib_index(46), 9)
        self.assertEqual(nearest_saved_fib_index(47), 9)
        self.assertEqual(nearest_saved_fib_index(48), 9)
        self.assertEqual(nearest_saved_fib_index(49), 9)
        self.assertEqual(nearest_saved_fib_index(50), 9)

if __name__ == '__main__':
    unittest.main()


# Corrected code
